# Generated by Django 5.1.11 on 2025-09-23 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livemusic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2025, 9, 23, 1, 36, 7, 226621, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
