# Generated by Django 5.1.11 on 2025-09-23 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livemusic', '0002_musicvenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicvenue',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
